name = "SimulationHPV"
uuid = "e510ab29-f908-4277-b8dc-2622eb127af1"
version = "0.0.1"
authors = ["AlexGotham <aleger567@gmail.com>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1.8.1"
Distributions = "0.25.122"
Roots = "2.2.10"
Statistics = "1.11.1"
julia = "1.10"
